<?php

namespace BookmarksApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BookmarkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookmarkRepository extends EntityRepository
{
    const BOOKMARKS_LIMIT = 10;

    public function getLatest()
    {
        return $this->createQueryBuilder('bookmark')
            ->select('bookmark.url')
            ->orderBy('bookmark.createdAt', 'desc')
            ->setMaxResults(self::BOOKMARKS_LIMIT)
            ->getQuery()
            ->getArrayResult();
    }
}
