<?php

namespace BookmarksApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function updateText($id, $text, $ip)
    {
        $datetime = new \DateTime();
        $datetime->sub(new \DateInterval('PT1H'));
        return $this->createQueryBuilder('commentupdate')
            ->update('\BookmarksApiBundle\Entity\Comment','c')
            ->set('c.text', ':text')
            ->where('c.ip = :ip')
            ->andWhere('c.createdAt >= :createdAt')
            ->andWhere('c.id = :id')
            ->setParameter('ip', $ip)
            ->setParameter('id', $id)
            ->setParameter('createdAt', $datetime)
            ->setParameter('text', $text)
            ->getQuery()
            ->execute();
    }

    public function deleteComment($id, $ip)
    {
        $datetime = new \DateTime();
        $datetime->sub(new \DateInterval('PT1H'));
        return $this->createQueryBuilder('comment')
            ->where('comment.ip= :ip')
            ->andWhere('comment.createdAt >= :createdAt')
            ->andWhere('comment.id= :id')
            ->setParameter('ip', $ip)
            ->setParameter('id', $id)
            ->setParameter('createdAt', $datetime)
            ->delete()
            ->getQuery()
            ->execute();
    }
}
